# Generated by Django 3.2.16 on 2024-02-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240206_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
